#!/bin/sh

# Copyright (c) 2015, Randy Westlund. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# This is a FreeBSD rc script for starting a node process and keeping it alive.
# It requires forever.js to be installed: 'npm install -g forever'.

# In addition to node_enable, the following rc variables should be defined:

# node_msg      The name of your program, printed at start. Defaults to "node".
# node_dir      The directory where your node files live. Must be defined.
# node_logdir   The directory for logfiles. Defaults to ${node_dir}/logs.
# node_user     User for both forever and the script. Defaults to "nobody".
# node_app      Application main script. Defaults to "/bin/www" (relative
#               to node_user's home
# node_forever  forever binary file path. Defaults to "/usr/local/bin/forever".
# node_local_forever    use local forever binary
#               (ie. node_user's home/node_modules/.bin/forever)
# node_forever_root     as specified in forever docs contains forever config 
#               and sockets for communicating with workers
# node_forever_log      forever log file. Defaults to /var/log/forever.log.

# PROVIDE: node
# REQUIRE: LOGIN mongod
# KEYWORD: shutdown

. /etc/rc.subr

name="node"
rcvar="${name}_enable"

start_precmd="${name}_prestart"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

# node executable
command="/usr/local/bin/${name}"

# forever needs a path for each command
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin

# get rc vars
load_rc_config $name
: ${node_enable:="no"}
: ${node_msg:="node"}
: ${node_logdir:="${node_dir}/logs"}
: ${node_user:="nobody"}
: ${node_app:="/bin/www"}
: ${node_forever:="/usr/local/bin/forever"}
: ${node_local_forever:="no"}
: ${node_forever_log:="${node_logdir}/forever.log"}
: ${node_forever_root:="/var/forever"}

export FOREVER_ROOT="${node_forever_root}"

case ${node_local_forever} in
    [Yy][Ee][Ss])
        node_forever="${node_dir}/node_modules/.bin/forever"
        ;;
    *)
        ;;
esac

# make sure we're pointing to the right place
required_dirs="${node_dir}"
required_files="${node_dir}/${node_app}"

command="${node_forever}"
# --pidFile ${pidfile}  -- let forever use default pid file, because it's woker's pid
command_args="start -a \
-l ${node_forever_log} \
-o ${node_logdir}/node.log \
-e ${node_logdir}/node_err.log \
--minUptime 3000 --spinSleepTime 1000000 \
--workingDir ${node_dir} \
${node_dir}/${node_app}"

# any other checks go here
node_prestart()
{
    mkdir "${node_forever_root}" 2>/dev/null
    chown "${node_user}" "${node_forever_root}"

    echo "$node_msg starting"
}

node_stop()
{
    ${node_forever} stop --killSignal SIGTERM "${node_dir}/${node_app}"
}

node_status()
{
    ${node_forever} list
}

run_rc_command "$1"

